title:              HILA Home
email:              
description:        A HPC framework and suite of Lattice Quantum Field Theory simulations
author:             HILA Maintainer and Contributors
baseurl:            "/"
url:                "https://insHILA-home.github.io"

# Social Profiles
twitter_username:   xxxxx
github_username:    xxxxx
gitlab_username:    xxxxx
bitbucket_username:    xxxxx 
linkedin_username:

# documentation page
docs_url: "https://cft-hy.github.io/HILA"

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
