title:              HILA Home
project_title:      HILA
email:              
description:        A HPC framework and suite of Lattice Quantum Field Theory simulations
author:             HILA Maintainer and Contributors

maintainer_url:        "https://www.mv.helsinki.fi/home/rummukai"
contributorsList_url:  "https://github.com/CFT-HY/HILA/graphs/contributors"  
baseurl:            "/"
url:                "https://insHILA-home.github.io"

# Social Profiles
twitter_username:   
github_repo:      "CFT-HY/HILA/tree/master"
gitlab_repo:       
bitbucket_repo:     
linkedin_username:

# documentation page
docs_url: "https://cft-hy.github.io/HILA"

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
# paginate:           5
# paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
